name: deploy-book

on:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: book
        environment-file: environment.yml
        python-version: 3.11
        auto-activate-base: false
        use-mamba: true

    - name: Build the book
      shell: bash -el {0}
      run: |
        jupyter-book build .
        
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
